### ISSUE TITLE
User distance setting set to miles but overview distance column shows kilometers

### ISSUE THREAD

**Issue by krisp** [wavelog/wavelog#1324]
I am using the latest version of the container under docker compose, which reports version as 1.8.8 in the debug menu. 

Server Software | Apache/2.4.62 (Debian)
PHP Version | 8.3.12 OK
MySQL Version | 11.3.2-MariaDB-1:11.3.2+maria~ubu2204
Codeigniter Version | 3.2.0-dev

**Steps to Reproduce**
Account -> Wavelog preferences
  Select Distance as a logbook column. 
  Select Miles as measurement distance.
  Scroll to bottom and click save.
Return to Logbook->Overview, observe distance column in km.

**Expected Behavior**
I expect this column to be displayed in miles.

**Additional Context**
I also noticed the account date format does not carry over to the Past QSO entry page which is where it is most needed but I found a separate bug for this and it looks like a more complicated issue.

**Comment by HB9HIL** [comment]
Hello @krisp 

this one was fixed last week and will be in the next release.

**Comment by WrathPak** [comment]
Hi there, Sorry I made a new issue. I figured I would come here and let you know I can confirm I am on 1.9 and this issue still persists.
