### ISSUE TITLE
Satellite Flightpath map not display

### ISSUE THREAD

**Issue by hellofinch** [wavelog/wavelog#1775]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the discussions area**

**Describe the bug**
map not show in Satellite Flightpath page.

**Version Information**
We need some information about your versions. You can get all Information in the Admin > Debug Menu
- OS:               linux
- PHP:              8.3.13
- MySQL/MariaDB:    10.6.18-MariaDB-0ubuntu0.22.04.1
- Wavelog:         dev-35333830

**Steps to Reproduce**
1. Go to 'Satellite Flightpath'
2. See error

**Expected Behavior**
The map may show below not blank. If the map works as designed, please let me know. : )

**Screenshots**
Include screenshots if applicable to illustrate the issue.

![Image](https://github.com/user-attachments/assets/92a35e8f-a3a6-4fa9-9357-82083d4fb42a)

**Additional Context**
I'm not sure that my network has trouble. But the main page has a map too and it shows fine.

: )

**Comment by AndreasK79** [comment]
@hellofinch seems I left the hardcoded tileurl in the code. I think #1776 should fix it. Can you test and confirm?

**Comment by hellofinch** [comment]
Thanks for your reply.
I pull the latest commit. But the map is still missing.

As you can see, I think the red space has some problems,too.
![Image](https://github.com/user-attachments/assets/7b3786f3-df20-4ec9-853b-f4847f313f20)

![Image](https://github.com/user-attachments/assets/87f8ee69-f620-4b6d-a92a-6eb249c7423f)

the map in the dashboard works fine.
![Image](https://github.com/user-attachments/assets/a141d0cf-298a-4cb7-af5f-51e5d249b9fd)

Have a nice day.
 : )

**Comment by AndreasK79** [comment]
@hellofinch this was not merged into dev. I merged the PR. Try to fetch latest dev now :)

**Comment by hellofinch** [comment]
Cool ! It works! Thanks!

73!
: )
